# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.download_pb2 as download__pb2


class DownloadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.doDownload = channel.unary_unary(
                '/downloadarff.Download/doDownload',
                request_serializer=download__pb2.DownloadRequest.SerializeToString,
                response_deserializer=download__pb2.DownloadReply.FromString,
                )


class DownloadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def doDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DownloadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'doDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.doDownload,
                    request_deserializer=download__pb2.DownloadRequest.FromString,
                    response_serializer=download__pb2.DownloadReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'downloadarff.Download', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Download(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def doDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/downloadarff.Download/doDownload',
            download__pb2.DownloadRequest.SerializeToString,
            download__pb2.DownloadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
