# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x04\x61uth\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\nLoginReply\x12\r\n\x05token\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"9\n\x13RegistrationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"6\n\x11RegistrationReply\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"D\n\rValidateReply\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x32\xbe\x01\n\x05Login\x12\x31\n\x07\x64oLogin\x12\x12.auth.LoginRequest\x1a\x10.auth.LoginReply\"\x00\x12\x46\n\x0e\x64oRegistration\x12\x19.auth.RegistrationRequest\x1a\x17.auth.RegistrationReply\"\x00\x12:\n\ndoValidate\x12\x15.auth.ValidateRequest\x1a\x13.auth.ValidateReply\"\x00\x42\x1e\n\x08../auth/B\nLoginProtoP\x01\xa2\x02\x03LOGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\010../auth/B\nLoginProtoP\001\242\002\003LOG'
  _globals['_LOGINREQUEST']._serialized_start=21
  _globals['_LOGINREQUEST']._serialized_end=71
  _globals['_LOGINREPLY']._serialized_start=73
  _globals['_LOGINREPLY']._serialized_end=121
  _globals['_REGISTRATIONREQUEST']._serialized_start=123
  _globals['_REGISTRATIONREQUEST']._serialized_end=180
  _globals['_REGISTRATIONREPLY']._serialized_start=182
  _globals['_REGISTRATIONREPLY']._serialized_end=236
  _globals['_VALIDATEREQUEST']._serialized_start=238
  _globals['_VALIDATEREQUEST']._serialized_end=270
  _globals['_VALIDATEREPLY']._serialized_start=272
  _globals['_VALIDATEREPLY']._serialized_end=340
  _globals['_LOGIN']._serialized_start=343
  _globals['_LOGIN']._serialized_end=533
# @@protoc_insertion_point(module_scope)
