apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploadcsv
  labels:
    app: uploadcsv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploadcsv
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: uploadcsv
    spec:
      containers:
        - name: uploadcsv
          image: valerio9723/uploadcsv
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: uploadcsv-configmap
            - secretRef:
                name: uploadcsv-secret
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 250m

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: uploadcsv-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uploadcsv
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 30