apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloadarff
  labels:
    app: downloadarff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloadarff
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: downloadarff
    spec:
      containers:
        - name: downloadarff
          image: valerio9723/downloadarff
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: downloadarff-configmap
            - secretRef:
                name: downloadarff-secret
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 250m

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: downloadarff-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: downloadarff
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 30