apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertercsv
  labels:
    app: convertercsv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convertercsv
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: convertercsv
    spec:
      containers:
        - name: convertercsv
          image: valerio9723/convertercsv
          envFrom:
            - configMapRef:
                name: convertercsv-configmap
            - secretRef:
                name: convertercsv-secret
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 250m

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: convertercsv-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: convertercsv
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 30